### ISSUE TITLE
It would be nice to have an image possibility as well

### ISSUE THREAD

**Issue by PhbsSmn** [mrlacey/VSWaterMark#10]
Currently it's only text that is being displayed.
Since I noticed that it was done with xaml, could it be extended with an image selection possibility as well?
It's more an enhancement rather than an issue.
Currently I was able to do it but needed to create a custom font.

Or maybe go the extra mile and forsee an editor like you could use to setup a signature in outlook.
Then you could use different markups through each other, when presenting a demo.

**Comment by mrlacey** [comment]
I love this suggestion. 

What if this was implemented by specifying a full path to an image file?
And then adding a separate flag to specify if should show the text or image. Or should it just use an image if one is specified and not have the extra configurable option?

An alternative would be to have a special indicator in the text field. So, you could specify something like `IMAGE:c:/dir/filename.png` and it would use the file specified there.


An invalid image path would be reported in the output window if encountered.

I don't _really_ want to support a mix of text and images. (It would get complicated and can be worked around by having an image with text in it.)

**Comment by PhbsSmn** [comment]
That could also be a path that could be followed it shouldn't get too overly complicated.
I will get through your code more deeply as well when I find the time. I'm interested in how this works.

**Comment by mrlacey** [comment]
> That could also be a path that could be followed it shouldn't get too overly complicated.

Do you mean a relative path? (e.g. "../../myfile.ext")
If so, where should the path be relative to? (the open file? the project root? the solution root? something else?)

I'm drawn to having to provide an absolute path so that there's no possibility for confusion. But, I'm open to arguments for where/when/why a relative path would be better or needed.

**Comment by PhbsSmn** [comment]
I would opt for an absolute path as well maybe my phrasing was a bit off causing an ambiguity that was unintended.

**Comment by mrlacey** [comment]
Initial experiment seems positive

![image](https://user-images.githubusercontent.com/189547/205746231-d3adb0ab-c495-488a-a75a-45d0a1cc3df1.png)

**Comment by mrlacey** [comment]
Version 1.8 is now in the marketplace and adds this capability.
Let me know how it works out for you or if you have any other suggestions for improvement.

**Comment by PhbsSmn** [comment]
It seems to be working nicely it gives more freedom to experiment like with QR codes and images mixed with each other now.
It also gives to power to go multicolor which was kind of hard to achieve with a font.

**Comment by mrlacey** [comment]
@PhbsSmn Glad it's helpful. A rating on the marketplace would be appreciated if you can https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WaterMark&ssr=false#review-details
