### ISSUE TITLE
I get "Unable to get name of the current file" frequently and constantly

### ISSUE THREAD

**Issue by szalapski** [mrlacey/VSWaterMark#11]
I sure do get a lot of "Unable to get name of the current file" even when it seems to be working just fine.  Any ideas on how to avoid this message?

![image](https://github.com/mrlacey/VSWaterMark/assets/2723505/1346f18e-e2f8-4cee-8bb3-efe33c56b8f5)

**Comment by mrlacey** [comment]
I've just released an update to the marketplace (v1.8.2) that should avoid the output window being unnecessarily filled with these messages.


If you have any problems, comments, or suggestions please raise another issue.
If you love it, please [leave a rating/review](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.WaterMark&ssr=false#review-details) or consider [sponsorship](https://github.com/sponsors/mrlacey)  :wink:

**Comment by szalapski** [comment]
Working great so far. :)
