### ISSUE TITLE
Enhancement idea: Show current filename in watermark

### ISSUE THREAD

**Issue by szalapski** [mrlacey/VSWaterMark#6]
It'd be cool if you could include the filename of the currently shown file in the text of the watermark.

Maybe there could be special string values that could be replaced, e.g. "mrlacey ${currentfilename}"  might show a watermark that changes appropriately, e.g. "mrlacey index.html" or "mrlacey appsettings.json".

**Comment by mrlacey** [comment]
It's a nice idea.
Beyond it being cool, what's the reason for wanting this?
Are there any other things (beyond the filename) that it would be useful to support?

**Comment by szalapski** [comment]
It actually really helps me to see the filename in larger font on the
bottom right, rather than trying to find the small text file name among
dozens of tabs.  I'm thinking for daily use, but perhaps also in
presentations as you intended.

**Comment by mrlacey** [comment]
In addition to just making the current filename more visible,  I've looked at other things for distinguishing between similar files and files with the same name but in different directories/projects.
I'm thinking it could be useful to add the following placeholders:

- ${currentfilename}
- ${currentdirectoryname}
- ${currentprojectname}

Hopefully, it's really obvious what they relate to.

Directory will be from the file path, and not any virtual folder or linked path inside the solution.

If they can't be determined (should only apply to the project one) then will get nothing (an empty string.)

Need to consider how to validate these placeholders and how to report

**Comment by szalapski** [comment]
Sounds perfect.

**Comment by mrlacey** [comment]
I've just released version 1.6 to the marketplace and that version adds this functionality.
Let me know if you have any issues with it.

**Comment by szalapski** [comment]
Works great, thanks!  Love it.

**Comment by szalapski** [comment]
The README says "$(currentFileName)" but I think it should read "${currentFileName}", right?

**Comment by mrlacey** [comment]
> The README says "$(currentFileName)" but I think it should read "${currentFileName}", right?

Oh, the readme on the marketplace. 🤦 
Yes, it should be with curly braces!

**Comment by mrlacey** [comment]
fixed ;)
