### ISSUE TITLE
Unable to display the water mark

### ISSUE THREAD

**Issue by SimpleCppCoder** [mrlacey/VSWaterMark#8]
Hello! I've been using this visual studio extension for quite a while now and I really enjoy it!
Sadly I have one issue with it, for a few months now I keep getting this error even if I uninstall and reinstall the extension:

> Unable to display the water mark
System.ArgumentException: Specified Visual is already a child of another Visual or the root of a CompositionTarget.
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at Microsoft.VisualStudio.Text.Editor.Implementation.AdornmentLayer.AddAdornment(AdornmentPositioningBehavior behavior, Nullable`1 visualSpan, Object tag, UIElement element, AdornmentRemovedCallback removedCallback)
   at VSWaterMark.WaterMarkAdornment.RefreshAdornment()
   
I am using Visual Studio 2022 and the latest version of the extension put up on the visual studio maketplace. (Appears to be 1.6)

This error appears when I open any files and it seems to have a side effect. If I scroll up towards the top of the file the water mark also moves up.
If I scroll towards the bottom of the page then the water mark moves down. It does go off of the screen if you scroll a lot.

**Comment by SimpleCppCoder** [comment]
Alright, so by disabling my other visual studio extensions one-by-one I found this other extension to be the issue: https://github.com/danielscherzer/GLSL
If I disable just that it appears to work

**Comment by mrlacey** [comment]
I don't have the other extension installed but still see the broken behavior.

Will investigate.....

**Comment by mrlacey** [comment]
I've just released version 1.7 to the marketplace, which fixes this issue.
Let me know if you have any further issues or suggestions for improvements.
